SettingsLib: Include WifiTrackerLib
We removed it at the commit below, but it
is still needed for CLO changes
Revert^2 "[RE-PICK] Remove WifiTrackerLib from SettingsLib"

This reverts commit b42c8a7d02bfa0ea904f91133d3b934166969f5f.

Reason for revert: Settings no longer needs it after I9f23d82db1a93e900d954ce8a5c8ecfa1388acde, and fixes build.

Change-Id: Iddfafd073c276b29cd4fa63b8e1442f8d3405705

Fixes
commit dd39885d1a9580da9633d6d2dd6bbd4d52b00348
Author: Chenming Huang <quic_chenhuan@quicinc.com>
Date:   Fri Sep 23 11:03:18 2022 +0800

    wifi: fix status bar wifi display abnormal

    Network name in status bar is directly from WifiInfo,
    which is expected to be hex digits if it's not utf-8
    encoding.

    This CL converts GBK encoding digits to readable text.

    CRs-Fixed: 3297467
    Change-Id: Ica57cfabc05ee9f9409fc6c9e1d46085f5da91db

frameworks/base/packages/SettingsLib/src/com/android/settingslib/wifi/WifiStatusTracker.java:39: error: cannot find symbol
import com.android.wifitrackerlib.WifiEntry;
                                 ^
  symbol:   class WifiEntry
  location: package com.android.wifitrackerlib
frameworks/base/packages/SettingsLib/src/com/android/settingslib/wifi/WifiStatusTracker.java:369: error: cannot find symbol
            if (WifiEntry.isGbkSsidSupported()) {
                ^
  symbol:   variable WifiEntry
  location: class WifiStatusTracker
frameworks/base/packages/SettingsLib/src/com/android/settingslib/wifi/WifiStatusTracker.java:370: error: cannot find symbol
                return com.android.wifitrackerlib.Utils.getReadableText(ssid);
                                                 ^
  symbol:   class Utils
  location: package com.android.wifitrackerlib

Change-Id: I3e28add5c10b4a726433cde6749e52cb3ee6b4eb